version: '3.8'

services:
#  app:
#    build:
#      context: ./app
#      dockerfile: ../Dockerfile
#      args:
#        ARTIFACT_NAME: app.jar
#    ports:
#      - 8081:8080
#    networks:
#      - backend-network
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend-network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - backend-network
  redis:
    image: redis:6.2.5-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend-network
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=db-tenpo-challenge
      - POSTGRES_USER=tenpo
      - POSTGRES_PASSWORD=tenpo
    ports:
      - "5432:5432"
    networks:
      - backend-network

networks:
  backend-network: