version: '3.8'

services:
#  app1:
#    build:
#      context: ./app1
#      dockerfile: ../Dockerfile
#      args:
#        ARTIFACT_NAME: app1.jar
#    ports:
#      - 8081:8080
#    networks:
#      - backend-network
#  kafka:
#    image: wurstmeister/kafka:2.12-2.8.0
#    ports:
#      - 9092:9092
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    networks:
#      - backend-network
#  zookeeper:
#    image: wurstmeister/zookeeper:3.4.6
#    ports:
#      - 2181:2181
#    networks:
#      - backend-network
  redis:
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379
    networks:
      - backend-network
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=db-tenpo-challenge
      - POSTGRES_USER=tenpo
      - POSTGRES_PASSWORD=tenpo
    ports:
      - '5432:5432'

networks:
  backend-network: